import { createContext } from "react";

export type Language = "BS" | "EN" | "DE";

export const LanguageContext = createContext({
  language: "BS" as Language,
  setLanguage: (lang: Language) => {},
  t: (key: string) => key
});

export const translations = {
  BS: {
    nav_about: "O nama",
    nav_services: "Usluge",
    nav_pricing: "Cjenovnik",
    nav_contact: "Kontakt",
    hero_subtitle: "EST. 2024 • MEDIA AGENCY",
    hero_title_1: "KREATIVNA",
    hero_title_2: "AGENCIJA",
    hero_desc: "Transformišemo digitalne vizije u tržišnu dominaciju.",
    scroll_down: "Skrolujte za više",
    about_label: "KO SMO MI",
    about_title_1: "Digitalna",
    about_title_2: "Revolucija.",
    about_desc: "Mios Media je hibridna agencija fokusirana na social-first strategije i high-end produkciju.",
    services_label: "NAŠE EKSPERTIZE",
    services_title_1: "Digitalne",
    services_title_2: "Ekspertize.",
    pricing_label: "INVESTICIJA U RAST",
    pricing_title_1: "Paketi &",
    pricing_title_2: "Investicije.",
    pricing_info: "Transparentan cjenovnik prilagođen vašim ciljevima.",
    contact_title_1: "Hajde da",
    contact_title_2: "rastemo.",
    footer_rights: "SVA PRAVA PRIDRŽANA",
    btn_inquiry: "Pošalji Upit",
    btn_details: "Zatvori detalje",
    production_label: "VIZUELNI STORYTELLING",
    production_title_1: "FOTO & VIDEO",
    production_title_2: "PRODUKCIJA",
    design_label: "BRANDING & IDENTITY",
    design_title_1: "GRAFIČKI",
    design_title_2: "DIZAJN",
    design_desc: "Kreiramo vizuelne identitete koji komuniciraju snagu i autoritet vašeg brenda.",
    web_label: "WEB DEVELOPMENT",
    web_title_1: "DIGITALNA",
    web_title_2: "PRISUTNOST",
    web_desc: "Od landing stranica do kompleksnih platformi, gradimo digitalna iskustva koja konvertuju.",
  },
  EN: {
    nav_about: "About",
    nav_services: "Services",
    nav_pricing: "Pricing",
    nav_contact: "Contact",
    hero_subtitle: "EST. 2024 • MEDIA AGENCY",
    hero_title_1: "CREATIVE",
    hero_title_2: "AGENCY",
    hero_desc: "Transforming digital visions into market dominance.",
    scroll_down: "Scroll to explore",
    about_label: "WHO WE ARE",
    about_title_1: "Digital",
    about_title_2: "Revolution.",
    about_desc: "Mios Media is a hybrid agency focused on social-first strategies and high-end production.",
    services_label: "OUR EXPERTISE",
    services_title_1: "Digital",
    services_title_2: "Expertise.",
    pricing_label: "GROWTH INVESTMENT",
    pricing_title_1: "Packages &",
    pricing_title_2: "Pricing.",
    pricing_info: "Transparent pricing models tailored to your business goals.",
    contact_title_1: "Let's",
    contact_title_2: "scale.",
    footer_rights: "ALL RIGHTS RESERVED",
    btn_inquiry: "Send Inquiry",
    btn_details: "Close details",
    production_label: "VISUAL STORYTELLING",
    production_title_1: "PHOTO & VIDEO",
    production_title_2: "PRODUCTION",
    design_label: "BRANDING & IDENTITY",
    design_title_1: "GRAPHIC",
    design_title_2: "DESIGN",
    design_desc: "We create visual identities that communicate the strength and authority of your brand.",
    web_label: "WEB DEVELOPMENT",
    web_title_1: "DIGITAL",
    web_title_2: "PRESENCE",
    web_desc: "From landing pages to complex platforms, we build digital experiences that convert.",
  },
  DE: {
    nav_about: "Über uns",
    nav_services: "Leistungen",
    nav_pricing: "Preise",
    nav_contact: "Kontakt",
    hero_subtitle: "EST. 2024 • MEDIA AGENTUR",
    hero_title_1: "KREATIVE",
    hero_title_2: "AGENTUR",
    hero_desc: "Wir verwandeln digitale Visionen in Marktbeherrschung.",
    scroll_down: "Scrollen zum Entdecken",
    about_label: "WER WIR SIND",
    about_title_1: "Digitale",
    about_title_2: "Revolution.",
    about_desc: "Mios Media ist eine Hybrid-Agentur, die sich auf Social-First-Strategien und High-End-Produktion konzentriert.",
    services_label: "UNSERE EXPERTISE",
    services_title_1: "Digitale",
    services_title_2: "Expertise.",
    pricing_label: "WACHSTUMSINVESTITION",
    pricing_title_1: "Pakete &",
    pricing_title_2: "Preise.",
    pricing_info: "Transparente Preismodelle, abgestimmt auf Ihre Geschäftsziele.",
    contact_title_1: "Lass uns",
    contact_title_2: "skalieren.",
    footer_rights: "ALLE RECHTE VORBEHALTEN",
    btn_inquiry: "Anfrage senden",
    btn_details: "Details schließen",
    production_label: "VISUELLES STORYTELLING",
    production_title_1: "FOTO & VIDEO",
    production_title_2: "PRODUKTION",
    design_label: "BRANDING & IDENTITÄT",
    design_title_1: "GRAFIK",
    design_title_2: "DESIGN",
    design_desc: "Wir schaffen visuelle Identitäten, die die Stärke und Autorität Ihrer Marke kommunizieren.",
    web_label: "WEB DEVELOPMENT",
    web_title_1: "DIGITALE",
    web_title_2: "PRÄSENZ",
    web_desc: "Von Landing Pages bis hin zu komplexen Plattformen bauen wir digitale Erlebnisse, die konvertieren.",
  }
};
