import { createContext } from "react";

export type Language = "BS" | "EN" | "DE";

export const LanguageContext = createContext({
  language: "BS" as Language,
  setLanguage: (lang: Language) => {},
  t: (key: string) => key
});

export const translations = {
  BS: {
    nav_about: "O nama",
    nav_services: "Usluge",
    nav_pricing: "Cjenovnik",
    nav_contact: "Kontakt",
    hero_subtitle: "EST. 2024 • MEDIA AGENCY",
    hero_title_1: "KREATIVNA",
    hero_title_2: "AGENCIJA",
    hero_desc: "Transformišemo digitalne vizije u tržišnu dominaciju.",
    scroll_down: "Skrolujte za više",
    about_label: "KO SMO MI",
    about_title_1: "Digitalna",
    about_title_2: "Revolucija.",
    about_desc: "Mios Media je hibridna agencija fokusirana na social-first strategije i high-end produkciju.",
    services_label: "NAŠE EKSPERTIZE",
    services_title_1: "Digitalne",
    services_title_2: "Ekspertize.",
    pricing_label: "INVESTICIJA U RAST",
    pricing_title_1: "Paketi &",
    pricing_title_2: "Investicije.",
    pricing_info: "Transparentan cjenovnik prilagođen vašim ciljevima.",
    contact_title_1: "Hajde da",
    contact_title_2: "rastemo.",
    footer_rights: "SVA PRAVA PRIDRŽANA",
    btn_inquiry: "Pošalji Upit",
    btn_details: "Zatvori detalje",
    label_currency: "Valuta",
    production_label: "VIZUELNI STORYTELLING",
    production_title_1: "FOTO & VIDEO",
    production_title_2: "PRODUKCIJA",
    design_label: "BRANDING & IDENTITY",
    design_title_1: "GRAFIČKI",
    design_title_2: "DIZAJN",
    design_desc: "Kreiramo vizuelne identitete koji komuniciraju snagu i autoritet vašeg brenda.",
    web_label: "WEB DEVELOPMENT",
    web_title_1: "DIGITALNA",
    web_title_2: "PRISUTNOST",
    web_desc: "Od landing stranica do kompleksnih platformi, gradimo digitalna iskustva koja konvertuju.",
    web_stack_desc: "Next.js, Tailwind & React za munjevit odziv.",
    service_modal_desc: "Premium usluga prilagođena rastu vašeg biznisa i tržišnom liderstvu.",
    btn_select_package: "ODABERI PAKET",
    label_most_popular: "NAJPOPULARNIJE",
    // Package features - Social
    feat_2_platforms: "2 platforme",
    feat_12_posts_monthly: "12 objava mjesečno",
    feat_community_management: "Upravljanje zajednicom",
    feat_basic_report: "Osnovni izvještaj",
    feat_story_design: "Dizajn story-ja",
    feat_3_platforms: "3 platforme",
    feat_20_posts_monthly: "20 objava mjesečno",
    feat_copywriting: "Pisanje sadržaja",
    feat_paid_ads_setup: "Postavljanje plaćenih oglasa",
    feat_monthly_analytics: "Mjesečna analitika",
    feat_all_platforms: "Sve platforme",
    feat_daily_posting: "Dnevno objavljivanje",
    feat_video_reels: "Video reels (4/mj)",
    feat_advanced_ads_strategy: "Napredna strategija oglasa",
    feat_dedicated_manager: "Dedikovani menadžer",
    // Package features - Web
    feat_single_page_site: "Jednostranačni sajt",
    feat_conversion_focus: "Konverzioni fokus",
    feat_mobile_responsive: "Mobilna prilagodljivost",
    feat_seo_setup: "SEO postavke",
    feat_1_year_support: "1 godina podrške",
    feat_multi_page_site: "Višestranačni sajt",
    feat_custom_cms: "Prilagođeni CMS",
    feat_blog_integration: "Blog integracija",
    feat_advanced_seo: "Napredni SEO",
    feat_copywriting_included: "Pisanje sadržaja uključeno",
    feat_online_store: "Online prodavnica",
    feat_payment_gateway: "Načini plaćanja",
    feat_inventory_management: "Upravljanje zalihama",
    feat_sales_automation: "Automatizacija prodaje",
    feat_work_instructions: "Uputstva za rad",
    // Package features - Production
    feat_logo_design: "Logo dizajn",
    feat_brand_guidelines: "Knjiga standarda",
    feat_business_cards: "Vizit karte dizajn",
    feat_banners_pack: "Paket banera",
    feat_print_prep: "Priprema za štampu",
    feat_professional_photo: "Profesionalna fotografija",
    feat_10_processed_images: "10 obrađenih slika",
    feat_short_form_video: "Kratki video (2)",
    feat_editing_included: "Montaža uključena",
    feat_commercial_rights: "Komercijalna prava",
    feat_quarterly_strategy: "Kvartalna strategija",
    feat_full_video_ad: "Puni video oglas (30s)",
    feat_photo_session: "Fotografisanje",
    feat_billboard_design: "Billboard dizajn",
    feat_pr_release: "PR objava",
    // Production services
    prod_photography_title: "Fotografija",
    prod_photography_desc: "Profesionalna fotografija proizvoda, enterijera i lifestyle portreta.",
    prod_cinematography_title: "Kinematografija",
    prod_cinematography_desc: "Snimanje visokokvalitetnih reklama i promotivnih videa.",
    prod_post_production_title: "Post-produkcija",
    prod_post_production_desc: "Montaža, color grading i sound design na vrhunskom nivou.",
    // Design features
    design_logo_brand_title: "Logo & Brand",
    design_logo_brand_desc: "Kreiramo bezvremenske logotipe i kompletne brand book-ove.",
    design_ui_title: "UI Design",
    design_ui_desc: "User-interface rješenja za aplikacije i sajtove visoke klase.",
    design_packaging_title: "Packaging",
    design_packaging_desc: "Dizajn ambalaže koji izdvaja vaš proizvod na polici.",
  },
  EN: {
    nav_about: "About",
    nav_services: "Services",
    nav_pricing: "Pricing",
    nav_contact: "Contact",
    hero_subtitle: "EST. 2024 • MEDIA AGENCY",
    hero_title_1: "CREATIVE",
    hero_title_2: "AGENCY",
    hero_desc: "Transforming digital visions into market dominance.",
    scroll_down: "Scroll to explore",
    about_label: "WHO WE ARE",
    about_title_1: "Digital",
    about_title_2: "Revolution.",
    about_desc: "Mios Media is a hybrid agency focused on social-first strategies and high-end production.",
    services_label: "OUR EXPERTISE",
    services_title_1: "Digital",
    services_title_2: "Expertise.",
    pricing_label: "GROWTH INVESTMENT",
    pricing_title_1: "Packages &",
    pricing_title_2: "Pricing.",
    pricing_info: "Transparent pricing models tailored to your business goals.",
    contact_title_1: "Let's",
    contact_title_2: "scale.",
    footer_rights: "ALL RIGHTS RESERVED",
    btn_inquiry: "Send Inquiry",
    btn_details: "Close details",
    label_currency: "Currency",
    production_label: "VISUAL STORYTELLING",
    production_title_1: "PHOTO & VIDEO",
    production_title_2: "PRODUCTION",
    design_label: "BRANDING & IDENTITY",
    design_title_1: "GRAPHIC",
    design_title_2: "DESIGN",
    design_desc: "We create visual identities that communicate the strength and authority of your brand.",
    web_label: "WEB DEVELOPMENT",
    web_title_1: "DIGITAL",
    web_title_2: "PRESENCE",
    web_desc: "From landing pages to complex platforms, we build digital experiences that convert.",
    web_stack_desc: "Next.js, Tailwind & React for lightning-fast performance.",
    service_modal_desc: "Premium service tailored for your business growth and market leadership.",
    btn_select_package: "SELECT PACKAGE",
    label_most_popular: "MOST POPULAR",
    // Package features - Social
    feat_2_platforms: "2 platforms",
    feat_12_posts_monthly: "12 posts monthly",
    feat_community_management: "Community management",
    feat_basic_report: "Basic report",
    feat_story_design: "Story design",
    feat_3_platforms: "3 platforms",
    feat_20_posts_monthly: "20 posts monthly",
    feat_copywriting: "Copywriting",
    feat_paid_ads_setup: "Paid Ads setup",
    feat_monthly_analytics: "Monthly analytics",
    feat_all_platforms: "All platforms",
    feat_daily_posting: "Daily posting",
    feat_video_reels: "Video reels (4/mo)",
    feat_advanced_ads_strategy: "Advanced Ads strategy",
    feat_dedicated_manager: "Dedicated manager",
    // Package features - Web
    feat_single_page_site: "Single page site",
    feat_conversion_focus: "Conversion focus",
    feat_mobile_responsive: "Mobile responsive",
    feat_seo_setup: "SEO setup",
    feat_1_year_support: "1 year support",
    feat_multi_page_site: "Multi-page site",
    feat_custom_cms: "Custom CMS",
    feat_blog_integration: "Blog integration",
    feat_advanced_seo: "Advanced SEO",
    feat_copywriting_included: "Copywriting included",
    feat_online_store: "Online store",
    feat_payment_gateway: "Payment gateway",
    feat_inventory_management: "Inventory management",
    feat_sales_automation: "Sales automation",
    feat_work_instructions: "Work instructions",
    // Package features - Production
    feat_logo_design: "Logo design",
    feat_brand_guidelines: "Brand guidelines",
    feat_business_cards: "Business card design",
    feat_banners_pack: "Banners pack",
    feat_print_prep: "Print prep",
    feat_professional_photo: "Professional photo",
    feat_10_processed_images: "10 processed images",
    feat_short_form_video: "Short-form video (2)",
    feat_editing_included: "Editing included",
    feat_commercial_rights: "Commercial rights",
    feat_quarterly_strategy: "Quarterly strategy",
    feat_full_video_ad: "Full video ad (30s)",
    feat_photo_session: "Photo session",
    feat_billboard_design: "Billboard design",
    feat_pr_release: "PR release",
    // Production services
    prod_photography_title: "Photography",
    prod_photography_desc: "Professional photography of products, interiors, and lifestyle portraits.",
    prod_cinematography_title: "Cinematography",
    prod_cinematography_desc: "Filming high-quality commercials and promotional videos.",
    prod_post_production_title: "Post-Production",
    prod_post_production_desc: "Editing, color grading, and sound design at the highest level.",
    // Design features
    design_logo_brand_title: "Logo & Brand",
    design_logo_brand_desc: "We create timeless logos and complete brand books.",
    design_ui_title: "UI Design",
    design_ui_desc: "User-interface solutions for high-class applications and websites.",
    design_packaging_title: "Packaging",
    design_packaging_desc: "Packaging design that makes your product stand out on the shelf.",
  },
  DE: {
    nav_about: "Über uns",
    nav_services: "Leistungen",
    nav_pricing: "Preise",
    nav_contact: "Kontakt",
    hero_subtitle: "EST. 2024 • MEDIA AGENTUR",
    hero_title_1: "KREATIVE",
    hero_title_2: "AGENTUR",
    hero_desc: "Wir verwandeln digitale Visionen in Marktbeherrschung.",
    scroll_down: "Scrollen zum Entdecken",
    about_label: "WER WIR SIND",
    about_title_1: "Digitale",
    about_title_2: "Revolution.",
    about_desc: "Mios Media ist eine Hybrid-Agentur, die sich auf Social-First-Strategien und High-End-Produktion konzentriert.",
    services_label: "UNSERE EXPERTISE",
    services_title_1: "Digitale",
    services_title_2: "Expertise.",
    pricing_label: "WACHSTUMSINVESTITION",
    pricing_title_1: "Pakete &",
    pricing_title_2: "Preise.",
    pricing_info: "Transparente Preismodelle, abgestimmt auf Ihre Geschäftsziele.",
    contact_title_1: "Lass uns",
    contact_title_2: "skalieren.",
    footer_rights: "ALLE RECHTE VORBEHALTEN",
    btn_inquiry: "Anfrage senden",
    btn_details: "Details schließen",
    label_currency: "Währung",
    production_label: "VISUELLES STORYTELLING",
    production_title_1: "FOTO & VIDEO",
    production_title_2: "PRODUKTION",
    design_label: "BRANDING & IDENTITÄT",
    design_title_1: "GRAFIK",
    design_title_2: "DESIGN",
    design_desc: "Wir schaffen visuelle Identitäten, die die Stärke und Autorität Ihrer Marke kommunizieren.",
    web_label: "WEB DEVELOPMENT",
    web_title_1: "DIGITALE",
    web_title_2: "PRÄSENZ",
    web_desc: "Von Landing Pages bis hin zu komplexen Plattformen bauen wir digitale Erlebnisse, die konvertieren.",
    web_stack_desc: "Next.js, Tailwind & React für blitzschnelle Performance.",
    service_modal_desc: "Premium-Service, der auf Ihr Geschäftswachstum und Ihre Marktführerschaft zugeschnitten ist.",
    btn_select_package: "PAKET AUSWÄHLEN",
    label_most_popular: "BELIEBTESTE",
    // Package features - Social
    feat_2_platforms: "2 Plattformen",
    feat_12_posts_monthly: "12 Beiträge monatlich",
    feat_community_management: "Community-Management",
    feat_basic_report: "Basisbericht",
    feat_story_design: "Story-Design",
    feat_3_platforms: "3 Plattformen",
    feat_20_posts_monthly: "20 Beiträge monatlich",
    feat_copywriting: "Texterstellung",
    feat_paid_ads_setup: "Paid Ads Einrichtung",
    feat_monthly_analytics: "Monatliche Analyse",
    feat_all_platforms: "Alle Plattformen",
    feat_daily_posting: "Tägliches Posten",
    feat_video_reels: "Video Reels (4/Mo)",
    feat_advanced_ads_strategy: "Erweiterte Ads-Strategie",
    feat_dedicated_manager: "Dedizierter Manager",
    // Package features - Web
    feat_single_page_site: "Einseitige Website",
    feat_conversion_focus: "Konversionsfokus",
    feat_mobile_responsive: "Mobil optimiert",
    feat_seo_setup: "SEO-Einrichtung",
    feat_1_year_support: "1 Jahr Support",
    feat_multi_page_site: "Mehrseitige Website",
    feat_custom_cms: "Individuelles CMS",
    feat_blog_integration: "Blog-Integration",
    feat_advanced_seo: "Erweiterte SEO",
    feat_copywriting_included: "Texterstellung inklusive",
    feat_online_store: "Online-Shop",
    feat_payment_gateway: "Zahlungsgateway",
    feat_inventory_management: "Bestandsverwaltung",
    feat_sales_automation: "Verkaufsautomatisierung",
    feat_work_instructions: "Arbeitsanweisungen",
    // Package features - Production
    feat_logo_design: "Logo-Design",
    feat_brand_guidelines: "Markenrichtlinien",
    feat_business_cards: "Visitenkarten-Design",
    feat_banners_pack: "Banner-Paket",
    feat_print_prep: "Druckvorbereitung",
    feat_professional_photo: "Professionelle Fotografie",
    feat_10_processed_images: "10 bearbeitete Bilder",
    feat_short_form_video: "Kurzvideo (2)",
    feat_editing_included: "Bearbeitung inklusive",
    feat_commercial_rights: "Kommerzielle Rechte",
    feat_quarterly_strategy: "Quartalsstrategie",
    feat_full_video_ad: "Vollständiger Video-Werbespot (30s)",
    feat_photo_session: "Fotosession",
    feat_billboard_design: "Plakatdesign",
    feat_pr_release: "PR-Veröffentlichung",
    // Production services
    prod_photography_title: "Fotografie",
    prod_photography_desc: "Professionelle Fotografie von Produkten, Innenräumen und Lifestyle-Porträts.",
    prod_cinematography_title: "Kinematografie",
    prod_cinematography_desc: "Drehen hochwertiger Werbespots und Werbevideos.",
    prod_post_production_title: "Postproduktion",
    prod_post_production_desc: "Schnitt, Farbkorrektur und Sounddesign auf höchstem Niveau.",
    // Design features
    design_logo_brand_title: "Logo & Marke",
    design_logo_brand_desc: "Wir erstellen zeitlose Logos und vollständige Brand Books.",
    design_ui_title: "UI-Design",
    design_ui_desc: "Benutzeroberflächenlösungen für hochwertige Anwendungen und Websites.",
    design_packaging_title: "Verpackung",
    design_packaging_desc: "Verpackungsdesign, das Ihr Produkt im Regal hervorhebt.",
  }
};
